Vagrant.configure("2") do |config|
  # On utilise une image officielle Debian 12 (Bookworm)
  config.vm.box = "debian/bookworm64"
  
  # On configure une carte réseau en DHCP, comme mentionné dans le TP
  config.vm.network "private_network", type: "dhcp"

  # Configuration spécifique pour VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "k3s-server"
    vb.memory = "2048" # Les 2Go de RAM recommandés
    vb.cpus = 2
  end
end