Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "k3s" do |k3s|
    k3s.vm.hostname = "k3s-server"
    k3s.vm.network "private_network", type: "dhcp"
    k3s.vm.provider "virtualbox" do |vb|
      vb.name = "k3s-server"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "monitoring" do |mon|
    mon.vm.hostname = "monitoring-server"
    mon.vm.network "private_network", type: "dhcp"
    mon.vm.provider "virtualbox" do |vb|
      vb.name = "monitoring-server"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end